spring:
  thymeleaf:
    mode: HTML
    cache: false
  main:
    allow-circular-references: true # 解决pagehelper依赖版本过低导致的"循环依赖"

  profiles:
    active: dev

  datasource: #连接数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2jd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: hyfhsy

comment:
  avatar: /image/IMG_2562.JPG

index:
    email: 1923326384@qq.com
    qq: 1923326384

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
    lazy-loading-enabled: true #开启延时加载开关
    aggressive-lazy-loading: false #将积极加载改为消极加载（即按需加载）,默认值就是false
    cache-enabled: true #打开全局缓存开关（二级环境），默认值就是true
  type-aliases-package: com.jxufe.entity #别名定义

#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true